Language: node_js
node_js:
  - 13
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"

script:
  - docker --version
  - docker build -t udagram-reverseproxy./udagram-reverseproxy
  - docker build -t udagram-api-feed/udagram-api-feed
  - docker build -t udagram-api-user/udagram-api-user
  - docker build -t udagram-frontend./udagram-frontend
  # Tagging
  - docker tag udagram-reverseproxy phucbv3/udagram-reverseproxy
  - docker tag udagram-api-feed phucbv3/udagram-api-feed
  - docker tag udagram-api-user phucbv3/udagram-api-user
  - docker tag udagram-frontend phucbv3/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phucbv3/udagram-reverseproxy
  - docker push phucbv3/udagram-api-feed
  - docker push phucbv3/udagram-api-user
  - docker push phucbv3/udagram-frontend