apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: api-user
        image: phucbv3/udagram-api-user:v1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080
